/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include "stm32f407xx.h"
#include "stm32f407xx_gpio_driver.h"
#include "stm32f407xx_usart_driver.h"

USART_Handle_t usart2_handle;

void USART2_Init(void)
{
	usart2_handle.pUSARTx = USART2;
	usart2_handle.USART_Config.USART_Baud = USART_STD_BAUD_9600;
	usart2_handle.USART_Config.USART_HWFlowControl = USART_HW_FLOW_CTRL_NONE;
	usart2_handle.USART_Config.USART_Mode = USART_MODE_ONLY_TX;
	usart2_handle.USART_Config.USART_NoOfStopBits = USART_STOPBITS_1;
	usart2_handle.USART_Config.USART_WordLength = USART_WORDLEN_8BITS;
	usart2_handle.USART_Config.USART_ParityControl = USART_PARITY_DISABLE;
	USART_Init(&usart2_handle);
}

void USART2_GPIOInit(void)
{
	GPIO_Handle_t usart_gpios;

	usart_gpios.pGPIOx = GPIOA;
	usart_gpios.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;
	usart_gpios.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	usart_gpios.GPIO_PinConfig.GPIO_PinPUPDControl = GPIO_PIN_PD ;
	usart_gpios.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_HIGH;
	usart_gpios.GPIO_PinConfig.GPIO_PinAltFunMode =7;

	//USART2 TX
	usart_gpios.GPIO_PinConfig.GPIO_PinNumber  = GPIO_PIN_NO_2;
	GPIO_Init(&usart_gpios);

	//USART2 RX
	usart_gpios.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_3;
	GPIO_Init(&usart_gpios);

}

void delay(void)
{
	for(uint32_t i = 0 ; i < 500000/2 ; i ++);
}

int main(void)
{

	USART_PeriClockControl(USART2  ,ENABLE) ;
	USART2_GPIOInit();


//	usart2_handle.pUSARTx->CR1 |= ( 1 << USART_CR1_OVER8) ;

    USART2_Init();

    USART_PeripheralControl(USART2,ENABLE);
//    USART_IRQInterruptConfig(38, ENABLE) ;

	delay();

	uint32_t k = 0 ;

	USART_printf(&usart2_handle, "this is int %d \n",k) ;
	USART_printf(&usart2_handle, "this is int %d \n",(k+=200000)) ;
	USART_printf(&usart2_handle, "this is int %d \n",(k+=200000)) ;
	USART_printf(&usart2_handle, "this is int %d \n",(k+=200000)) ;

	USART_printf(&usart2_handle, "this is string %s \n","this is pratham vora 01") ;
	USART_printf(&usart2_handle, "this is string %s \n","this is short text") ;
	USART_printf(&usart2_handle, "this is string %s \n","this is nothing ") ;
	USART_printf(&usart2_handle, "this is string %s \n","this is very very very very very very long text ") ;

	USART_printf(&usart2_handle, "this is char %c \n",'a') ;
	USART_printf(&usart2_handle, "this is char %c \n",'b') ;
	USART_printf(&usart2_handle, "this is char %c \n",'c') ;
	USART_printf(&usart2_handle, "this is char %c \n",'d') ;

	USART_printf(&usart2_handle, "this is hex %x \n",1024) ;
	USART_printf(&usart2_handle, "this is hex %x \n",2048) ;
	USART_printf(&usart2_handle, "this is hex %x \n",4096) ;
	USART_printf(&usart2_handle, "this is hex %x \n",8192) ;


	return 0;
}

void USART2_IRQHandler(){
USART_IRQHandling(&usart2_handle) ;
}
